---
# Server settings
server:
  port: 9198
  servlet:
    context-path: /ownerapi

testInt: 11
testString: microservices


# H2 Settings
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console: 
      enabled: true
      path: /h2-console

# Hibernate & JPA settings
  jackson:
    serialization:
      indent_output: true
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    hibernate:
    ddl-auto: create
#spring.jpa.show-sql=true
    properties:
      hibernate:
        format_sql: true
